/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavItems: typeof import('./src/components/navigation/AdminNavItems.vue')['default']
    AllDisplayed: typeof import('./src/components/common/AllDisplayed.vue')['default']
    AppSetting: typeof import('./src/components/common/AppSetting.vue')['default']
    AppSettingsCard: typeof import('./src/components/settings/AppSettingsCard.vue')['default']
    BoxesList: typeof import('./src/components/storage/rooms/BoxesList.vue')['default']
    BoxSummaryCard: typeof import('./src/components/storage/boxes/BoxSummaryCard.vue')['default']
    BoxSummaryList: typeof import('./src/components/storage/boxes/BoxSummaryList.vue')['default']
    CategoryChip: typeof import('./src/components/common/CategoryChip.vue')['default']
    ConfirmBoxDeleteModal: typeof import('./src/components/storage/boxes/ConfirmBoxDeleteModal.vue')['default']
    ConfirmHouseholdActionDialog: typeof import('./src/components/household/dialogs/ConfirmHouseholdActionDialog.vue')['default']
    ConfirmHouseholdDeleteDialog: typeof import('./src/components/household/dialogs/ConfirmHouseholdDeleteDialog.vue')['default']
    ConfirmItemDeleteDialog: typeof import('./src/components/items/modals/ConfirmItemDeleteDialog.vue')['default']
    ConfirmKickFromHouseholdDialog: typeof import('./src/components/household/dialogs/ConfirmKickFromHouseholdDialog.vue')['default']
    COnfirmKickFromHouseholdDialog: typeof import('./src/components/household/dialogs/COnfirmKickFromHouseholdDialog.vue')['default']
    ConfirmLeaveDialog: typeof import('./src/components/common/modals/ConfirmLeaveDialog.vue')['default']
    ConfirmRoomDeleteModal: typeof import('./src/components/storage/rooms/modals/ConfirmRoomDeleteModal.vue')['default']
    ConfirmTransferHouseholdDialog: typeof import('./src/components/household/dialogs/ConfirmTransferHouseholdDialog.vue')['default']
    CreateBoxModal: typeof import('./src/components/storage/boxes/modals/CreateBoxModal.vue')['default']
    CreateCategoryModal: typeof import('./src/components/categories/CreateCategoryModal.vue')['default']
    CreateHouseholdCard: typeof import('./src/components/household/CreateHouseholdCard.vue')['default']
    CreateItemModal: typeof import('./src/components/items/modals/CreateItemModal.vue')['default']
    CreateNewUser: typeof import('./src/components/admin/CreateNewUser.vue')['default']
    CreateRoomModal: typeof import('./src/components/storage/rooms/CreateRoomModal.vue')['default']
    EditBoxModal: typeof import('./src/components/storage/boxes/modals/EditBoxModal.vue')['default']
    EditItemDialog: typeof import('./src/components/items/modals/EditItemDialog.vue')['default']
    EditItemInstanceDialog: typeof import('./src/components/items/modals/EditItemInstanceDialog.vue')['default']
    EditRoomModal: typeof import('./src/components/storage/rooms/modals/EditRoomModal.vue')['default']
    FabItems: typeof import('./src/components/navigation/FabItems.vue')['default']
    ForgotPassword: typeof import('./src/components/account/forgot-password.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    HouseholdCard: typeof import('./src/components/household/HouseholdCard.vue')['default']
    HouseholdInvite: typeof import('./src/components/household/HouseholdInvite.vue')['default']
    HouseholdMemberCard: typeof import('./src/components/household/HouseholdMemberCard.vue')['default']
    HouseholdQuickSelectCard: typeof import('./src/components/household/HouseholdQuickSelectCard.vue')['default']
    InfoBanner: typeof import('./src/components/common/InfoBanner.vue')['default']
    InventoryHeroLabel: typeof import('./src/components/qr/InventoryHeroLabel.vue')['default']
    ItemDetailCard: typeof import('./src/components/items/ItemDetailCard.vue')['default']
    ItemDetailHeader: typeof import('./src/components/items/ItemDetailHeader.vue')['default']
    ItemDetailStoragePanel: typeof import('./src/components/items/ItemDetailStoragePanel.vue')['default']
    ItemInstanceStoragePanel: typeof import('./src/components/items/ItemInstanceStoragePanel.vue')['default']
    ItemList: typeof import('./src/components/storage/rooms/ItemList.vue')['default']
    ItemSummaryCard: typeof import('./src/components/items/ItemSummaryCard.vue')['default']
    ItemSummaryList: typeof import('./src/components/items/ItemSummaryList.vue')['default']
    NavItems: typeof import('./src/components/navigation/NavItems.vue')['default']
    NumberInputSlider: typeof import('./src/components/qr/NumberInputSlider.vue')['default']
    PageConfiguration: typeof import('./src/components/qr/PageConfiguration.vue')['default']
    PagePreview: typeof import('./src/components/qr/PagePreview.vue')['default']
    PasswordTextField: typeof import('./src/components/common/PasswordTextField.vue')['default']
    RoomContentHeader: typeof import('./src/components/storage/rooms/RoomContentHeader.vue')['default']
    RoomSummaryCard: typeof import('./src/components/storage/rooms/RoomSummaryCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanLabel: typeof import('./src/components/qr/modals/ScanLabel.vue')['default']
    SearchCard: typeof import('./src/components/common/SearchCard.vue')['default']
    TabView: typeof import('./src/components/qr/TabView.vue')['default']
    TestEmailDialog: typeof import('./src/components/admin/TestEmailDialog.vue')['default']
    UiSettings: typeof import('./src/components/settings/UiSettings.vue')['default']
  }
}
