/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/account': RouteRecordInfo<
      '/account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administration': RouteRecordInfo<
      '/administration',
      '/administration',
      Record<never, never>,
      Record<never, never>,
      | '/administration/'
      | '/administration/users/'
      | '/administration/users/user.[id]'
    >,
    '/administration/': RouteRecordInfo<
      '/administration/',
      '/administration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administration/users/': RouteRecordInfo<
      '/administration/users/',
      '/administration/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/administration/users/user.[id]': RouteRecordInfo<
      '/administration/users/user.[id]',
      '/administration/users/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/confirmation': RouteRecordInfo<
      '/confirmation',
      '/confirmation',
      Record<never, never>,
      Record<never, never>,
      | '/confirmation/confirm.[code]'
    >,
    '/confirmation/confirm.[code]': RouteRecordInfo<
      '/confirmation/confirm.[code]',
      '/confirmation/confirm/:code',
      { code: ParamValue<true> },
      { code: ParamValue<false> },
      | never
    >,
    '/households/': RouteRecordInfo<
      '/households/',
      '/households',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/households/[id]': RouteRecordInfo<
      '/households/[id]',
      '/households/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/households/join.[code]': RouteRecordInfo<
      '/households/join.[code]',
      '/households/join/:code',
      { code: ParamValue<true> },
      { code: ParamValue<false> },
      | never
    >,
    '/items/': RouteRecordInfo<
      '/items/',
      '/items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/items/[id]': RouteRecordInfo<
      '/items/[id]',
      '/items/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/logout': RouteRecordInfo<
      '/login/logout',
      '/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/password-reset.[id]': RouteRecordInfo<
      '/login/password-reset.[id]',
      '/password-reset/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login/register': RouteRecordInfo<
      '/login/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/qr/': RouteRecordInfo<
      '/qr/',
      '/qr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/storage/boxes/': RouteRecordInfo<
      '/storage/boxes/',
      '/storage/boxes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/storage/boxes/box.[id]': RouteRecordInfo<
      '/storage/boxes/box.[id]',
      '/storage/boxes/box/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/storage/rooms/': RouteRecordInfo<
      '/storage/rooms/',
      '/storage/rooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/storage/rooms/room.[id]': RouteRecordInfo<
      '/storage/rooms/room.[id]',
      '/storage/rooms/room/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/account.vue': {
      routes:
        | '/account'
      views:
        | never
    }
    'src/pages/administration.vue': {
      routes:
        | '/administration'
        | '/administration/'
        | '/administration/users/'
        | '/administration/users/user.[id]'
      views:
        | 'default'
    }
    'src/pages/administration/index.vue': {
      routes:
        | '/administration/'
      views:
        | never
    }
    'src/pages/administration/users/index.vue': {
      routes:
        | '/administration/users/'
      views:
        | never
    }
    'src/pages/administration/users/user.[id].vue': {
      routes:
        | '/administration/users/user.[id]'
      views:
        | never
    }
    'src/pages/confirmation.vue': {
      routes:
        | '/confirmation'
        | '/confirmation/confirm.[code]'
      views:
        | 'default'
    }
    'src/pages/confirmation/confirm.[code].vue': {
      routes:
        | '/confirmation/confirm.[code]'
      views:
        | never
    }
    'src/pages/households/index.vue': {
      routes:
        | '/households/'
      views:
        | never
    }
    'src/pages/households/[id].vue': {
      routes:
        | '/households/[id]'
      views:
        | never
    }
    'src/pages/households/join.[code].vue': {
      routes:
        | '/households/join.[code]'
      views:
        | never
    }
    'src/pages/items/index.vue': {
      routes:
        | '/items/'
      views:
        | never
    }
    'src/pages/items/[id].vue': {
      routes:
        | '/items/[id]'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/login/logout.vue': {
      routes:
        | '/login/logout'
      views:
        | never
    }
    'src/pages/login/password-reset.[id].vue': {
      routes:
        | '/login/password-reset.[id]'
      views:
        | never
    }
    'src/pages/login/register.vue': {
      routes:
        | '/login/register'
      views:
        | never
    }
    'src/pages/qr/index.vue': {
      routes:
        | '/qr/'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/storage/boxes/index.vue': {
      routes:
        | '/storage/boxes/'
      views:
        | never
    }
    'src/pages/storage/boxes/box.[id].vue': {
      routes:
        | '/storage/boxes/box.[id]'
      views:
        | never
    }
    'src/pages/storage/rooms/index.vue': {
      routes:
        | '/storage/rooms/'
      views:
        | never
    }
    'src/pages/storage/rooms/room.[id].vue': {
      routes:
        | '/storage/rooms/room.[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
