/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/confirmation': RouteRecordInfo<'/confirmation', '/confirmation', Record<never, never>, Record<never, never>, '/confirmation/confirm.[code]'>,
    '/confirmation/confirm.[code]': RouteRecordInfo<'/confirmation/confirm.[code]', '/confirmation/confirm/:code', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/households/': RouteRecordInfo<'/households/', '/households', Record<never, never>, Record<never, never>>,
    '/households/[id]': RouteRecordInfo<'/households/[id]', '/households/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/households/join.[code]': RouteRecordInfo<'/households/join.[code]', '/households/join/:code', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    '/items/': RouteRecordInfo<'/items/', '/items', Record<never, never>, Record<never, never>>,
    '/items/[id]': RouteRecordInfo<'/items/[id]', '/items/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/logout': RouteRecordInfo<'/login/logout', '/logout', Record<never, never>, Record<never, never>>,
    '/login/password-reset.[id]': RouteRecordInfo<'/login/password-reset.[id]', '/password-reset/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login/register': RouteRecordInfo<'/login/register', '/register', Record<never, never>, Record<never, never>>,
    '/login/settings': RouteRecordInfo<'/login/settings', '/login/settings', Record<never, never>, Record<never, never>>,
    '/qr/': RouteRecordInfo<'/qr/', '/qr', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/storage/boxes/': RouteRecordInfo<'/storage/boxes/', '/storage/boxes', Record<never, never>, Record<never, never>>,
    '/storage/boxes/box.[id]': RouteRecordInfo<'/storage/boxes/box.[id]', '/storage/boxes/box/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/storage/rooms/': RouteRecordInfo<'/storage/rooms/', '/storage/rooms', Record<never, never>, Record<never, never>>,
    '/storage/rooms/room.[id]': RouteRecordInfo<'/storage/rooms/room.[id]', '/storage/rooms/room/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
