version: "3.4"
services:
  inventoryhero:
    container_name: inventory-hero-dev
    image: inventoryhero:dev
    build:
      target: dev
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./dev/test.db:/db/test.db
    ports:
      - 8080:80
      - 5000:5000
    env_file:
      - .env
      