"""DateTime now TZ aware

Revision ID: 9890d39dfffd
Revises: ee578f36fbd3
Create Date: 2025-11-01 14:08:37.268702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utc
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9890d39dfffd'
down_revision: Union[str, None] = 'ee578f36fbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('registered_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('registered_on',
               existing_type=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
