"""AddOidcSub

Revision ID: 7d789b5a152a
Revises: df48774838d9
Create Date: 2025-11-06 15:35:51.326496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision: str = '7d789b5a152a'
down_revision: Union[str, None] = 'df48774838d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oidc_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_oidc_sub'), ['oidc_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_oidc_sub'))
        batch_op.drop_column('oidc_sub')

    # ### end Alembic commands ###
