"""AddAuthenticationProvider

Revision ID: df48774838d9
Revises: 9890d39dfffd
Create Date: 2025-11-06 14:44:33.894250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision: str = 'df48774838d9'
down_revision: Union[str, None] = '9890d39dfffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=False, server_default='local'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
