"""set user's household to null if delete

Revision ID: 28a173fea5fe
Revises: 667cf35f0d9b
Create Date: 2025-04-23 11:35:47.032423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28a173fea5fe'
down_revision: Union[str, None] = '667cf35f0d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_household_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'household', ['household'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_household_fkey', 'user', 'household', ['household'], ['id'])
    # ### end Alembic commands ###
