"""household member has joined field

Revision ID: 63c0f87976f3
Revises: 28a173fea5fe
Create Date: 2025-04-25 08:50:48.045429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63c0f87976f3'
down_revision: Union[str, None] = '28a173fea5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('householdmember', sa.Column('joined', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('householdmember', 'joined')
    # ### end Alembic commands ###
