"""household invites add inviter id

Revision ID: 64165982b54d
Revises: 88478dacd058
Create Date: 2025-04-26 16:31:34.201810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64165982b54d'
down_revision: Union[str, None] = '88478dacd058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('householdinvite', sa.Column('inviter', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'householdinvite', 'user', ['inviter'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'householdinvite', type_='foreignkey')
    op.drop_column('householdinvite', 'inviter')
    # ### end Alembic commands ###
