"""households

Revision ID: 667cf35f0d9b
Revises: ffc8b5b72c90
Create Date: 2025-04-22 12:14:22.439008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '667cf35f0d9b'
down_revision: Union[str, None] = 'ffc8b5b72c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_id'), 'household', ['id'], unique=False)
    op.create_index(op.f('ix_household_name'), 'household', ['name'], unique=False)
    op.create_table('householdmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_householdmember_id'), 'householdmember', ['id'], unique=False)
    op.add_column('user', sa.Column('household', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'household', ['household'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'household')
    op.drop_index(op.f('ix_householdmember_id'), table_name='householdmember')
    op.drop_table('householdmember')
    op.drop_index(op.f('ix_household_name'), table_name='household')
    op.drop_index(op.f('ix_household_id'), table_name='household')
    op.drop_table('household')
    # ### end Alembic commands ###
