"""cascade delete for items

Revision ID: 67159ae39df8
Revises: a0db01543d72
Create Date: 2025-06-27 11:42:26.420782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67159ae39df8'
down_revision: Union[str, None] = 'a0db01543d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_name', table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.drop_constraint('item_household_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'household', ['household_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('itemcategorylink_category_id_fkey', 'itemcategorylink', type_='foreignkey')
    op.drop_constraint('itemcategorylink_item_id_fkey', 'itemcategorylink', type_='foreignkey')
    op.create_foreign_key(None, 'itemcategorylink', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'itemcategorylink', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itemcategorylink', type_='foreignkey')
    op.drop_constraint(None, 'itemcategorylink', type_='foreignkey')
    op.create_foreign_key('itemcategorylink_item_id_fkey', 'itemcategorylink', 'item', ['item_id'], ['id'])
    op.create_foreign_key('itemcategorylink_category_id_fkey', 'itemcategorylink', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_household_id_fkey', 'item', 'household', ['household_id'], ['id'])
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index('ix_category_name', 'category', ['name'], unique=True)
    # ### end Alembic commands ###
