"""storage ondelete

Revision ID: 80fb232138c1
Revises: a4178de77f42
Create Date: 2025-07-26 13:29:44.084511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80fb232138c1'
down_revision: Union[str, None] = 'a4178de77f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('storage_parent_id_fkey', 'storage', type_='foreignkey')
    op.create_foreign_key(None, 'storage', 'storage', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.create_foreign_key('storage_parent_id_fkey', 'storage', 'storage', ['parent_id'], ['id'])
    # ### end Alembic commands ###

