"""household member user only once per household

Revision ID: 8201d0df3383
Revises: f05686ccb408
Create Date: 2025-04-27 11:39:49.838768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8201d0df3383'
down_revision: Union[str, None] = 'f05686ccb408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_in_household_unique', 'householdmember', ['household_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_in_household_unique', 'householdmember', type_='unique')
    # ### end Alembic commands ###
