"""household invites email + household_id is unique

Revision ID: 88478dacd058
Revises: 8e701d7c7e9f
Create Date: 2025-04-26 13:20:43.046266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88478dacd058'
down_revision: Union[str, None] = '8e701d7c7e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_invite_per_household_email', 'householdinvite', ['household_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_invite_per_household_email', 'householdinvite', type_='unique')
    # ### end Alembic commands ###
