"""household invites non nullable email

Revision ID: 8e701d7c7e9f
Revises: 6679d1e6ccf9
Create Date: 2025-04-26 11:54:13.651646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e701d7c7e9f'
down_revision: Union[str, None] = '6679d1e6ccf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('householdinvite', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('householdinvite', 'invited_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('householdinvite', sa.Column('invited_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('householdinvite', 'email')
    # ### end Alembic commands ###
