"""added household_id to category

Revision ID: a0db01543d72
Revises: ad2cc61fe1ab
Create Date: 2025-06-20 22:47:15.028528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0db01543d72'
down_revision: Union[str, None] = 'ad2cc61fe1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('household_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'category', 'household', ['household_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'household_id')
    # ### end Alembic commands ###
