"""password reset token

Revision ID: bd2d7adde6b1
Revises: 56239b82635c
Create Date: 2025-07-22 08:15:53.655347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd2d7adde6b1'
down_revision: Union[str, None] = '56239b82635c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('password_reset_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_reset_token_expires_at')
    op.drop_column('user', 'password_reset_token')
    # ### end Alembic commands ###
