"""household invites remove email - overkill

Revision ID: f05686ccb408
Revises: 64165982b54d
Create Date: 2025-04-27 10:09:12.860700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f05686ccb408'
down_revision: Union[str, None] = '64165982b54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_invite_per_household_email', 'householdinvite', type_='unique')
    op.drop_column('householdinvite', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('householdinvite', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('unique_invite_per_household_email', 'householdinvite', ['household_id', 'email'])
    # ### end Alembic commands ###
