"""added basic storage

Revision ID: f1b6775fe8d9
Revises: 81fe91b4671b
Create Date: 2025-05-10 18:23:32.211355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1b6775fe8d9'
down_revision: Union[str, None] = '81fe91b4671b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_type', sa.Enum('ROOM', 'BOX', name='storagetype'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_name'), 'storage', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_name'), table_name='storage')
    op.drop_table('storage')
    # ### end Alembic commands ###
