"""empty message

Revision ID: 01ff6198f7ea
Revises: 65062e77f973
Create Date: 2024-09-04 16:26:27.738946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ff6198f7ea'
down_revision = '65062e77f973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=65535), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_container_mapping', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'storage', ['storage_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_container_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('storage')
    # ### end Alembic commands ###
