"""empty message

Revision ID: 2af36806627e
Revises: 87f7cdf81436
Create Date: 2024-09-08 09:22:12.590286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af36806627e'
down_revision = '87f7cdf81436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_constraint('household_creator_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.drop_constraint('household_members_member_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('household_members_household_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'household', ['household_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.drop_constraint('password_reset_requests_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.drop_constraint('storage_household_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'household', ['household_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('storage_household_id_fkey', 'household', ['household_id'], ['id'])

    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('password_reset_requests_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('household_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('household_members_household_id_fkey', 'household', ['household_id'], ['id'])
        batch_op.create_foreign_key('household_members_member_id_fkey', 'user', ['member_id'], ['id'])

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('household_creator_fkey', 'user', ['creator'], ['id'])

    # ### end Alembic commands ###
