"""empty message

Revision ID: 31cebef611d0
Revises: faa42196b50f
Create Date: 2024-09-08 17:07:21.584790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cebef611d0'
down_revision = 'faa42196b50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_reset', sa.Boolean(), nullable=True, server_default=sa.false()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_reset')

    # ### end Alembic commands ###
