"""empty message

Revision ID: 65062e77f973
Revises: eea3206d6d54
Create Date: 2024-09-04 11:37:14.423767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65062e77f973'
down_revision = 'eea3206d6d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint('token_blacklist_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('token_blacklist_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
