"""empty message

Revision ID: faa42196b50f
Revises: 2af36806627e
Create Date: 2024-09-08 09:27:52.453554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa42196b50f'
down_revision = '2af36806627e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_container_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('product_container_mapping_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_household_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'household', ['household_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_household_id_fkey', 'household', ['household_id'], ['id'])

    with op.batch_alter_table('product_container_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_container_mapping_product_id_fkey', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
